import os

from build_ffmpeg import build_ffmpeg

print('-= Running Sconscript - gozen_ffmpeg =-')

env = SConscript("../godot_cpp/SConstruct")
env.Append(CPPPATH=["src/"])
num_jobs = ARGUMENTS.get('jobs', 4)

platform = ARGUMENTS.get('platform', 'Linux') # If no platform gets given, compiling for Linux
use_mingw = ARGUMENTS.get('use_mingw', 'no')
if platform == "linux": # Linux
    env.Append(LIBS=["avcodec", "avformat", "avfilter", "avdevice", "avutil", "swscale", "swresample"])
elif platform == "windows": # Windows
    # Adding libraries for building
    build_ffmpeg(num_jobs)
    env.Append(CPPPATH=["ffmpeg-bin/include"])
    env.Append(LIBPATH=["ffmpeg-bin/bin"])
    env.Append(LIBS=["avcodec", "avformat", "avfilter", "avdevice", "avutil", "swscale", "swresample"])
    if use_mingw == "no": # Mingw is used for compiling on Linux for Windows
        env.Append(LINKFLAGS=["avcodec.lib", "avformat.lib", "avfilter.lib", "avdevice.lib", "avutil.lib", "swscale.lib", "swresample.lib"])
elif platform == "macos": # MacOS - TODO: not working
    env.Append(LIBS=["libavcodec", "libavformat", "libavfilter", "libavdevice", "libavutil", "libswscale", "libswresample"])

src = Glob("src/*.cpp")
libpath = "../../src/bin/libgozen{}{}".format(env["suffix"], env["SHLIBSUFFIX"])

sharedlib = env.SharedLibrary(libpath, src)
Default(sharedlib)

print("libpath:", libpath)
print('-= Compiling gozen_ffmpeg complete =-')
