class_name Library
extends Node


const ICON_GOZEN: String = "uid://cwv5gaisvmwv7"
const ICON_PLAY: String = "uid://mk4pnxw14y5q"
const ICON_PAUSE: String = "uid://bvfdrqumef0br"
const ICON_RENDERING: String = "uid://b6r37nt1xhvq6"
const ICON_SAVE: String = "uid://bbbs474i3jn8p"
const ICON_OPEN: String = "uid://17gcpvhkgkjl"
const ICON_CLOSE: String = "uid://kqv3ky2283ed"
const ICON_EDITOR_SETTINGS: String = "uid://cw6unlqdkehwq"
const ICON_PROJECT_SETTINGS: String = "uid://coy178c5y4de5"
const ICON_EFFECT_SETTINGS: String = "uid://bod60hmll7nle"
const ICON_LINK: String = "uid://brk03ymljvaym"
const ICON_MANUAL: String = "uid://cgetxovfmpffg"
const ICON_TUTORIALS: String = "uid://43v154g7ibyl"
const ICON_SUPPORT: String = "uid://kll463gy1ppm"
const ICON_ABOUT_GOZEN: String = "uid://dc4wlfsk1n7wy"
const ICON_BUTTON_FADE: String = "uid://b77qf524y84nn"
const ICON_SEARCH: String = "uid://dmqhsyh4vjsnp"
const ICON_ADD: String = "uid://ca5yfytbff5wr"
const ICON_DELETE: String = "uid://cm8roaxbwvyv8"
const ICON_FOLDER: String = "uid://17gcpvhkgkjl"
const ICON_REFRESH: String = "uid://dyhdfp543l3fa"
const ICON_PREV_KEYFRAME: String = "uid://rpl4xa83uh1k"
const ICON_NEXT_KEYFRAME: String = "uid://d3uu1keaic7ux"
const ICON_MOVE_HANDLE: String = "uid://cegumbgegg2fm"
const ICON_VISIBLE: String = "uid://b320ug5wgphpu"
const ICON_INVISIBLE: String = "uid://bx21sefl65fu2"
const ICON_EFFECT_KEYFRAME: String = "uid://dy304t3w87gdp"
const ICON_EFFECT_KEYFRAME_EMPTY: String = "uid://bn2htabj05tcs"
const ICON_EFFECTS_KEYFRAME: String = "uid://4my3sfu0fkon"
const ICON_EFFECTS_KEYFRAME_EMPTY: String = "uid://ndhtkbq6ld0p"
const ICON_TIMELINE_MODE_SELECT: String = "uid://de7u45155mub0"
const ICON_TIMELINE_MODE_SPLIT: String = "uid://vrkhavabr26v"
const ICON_CUSTOM_RENDER_PROFILE: String = "uid://spvmd3g0xi3t"
const ICON_SNAP_ON: String = "uid://blw00i0hrh0x8"
const ICON_SNAP_OFF: String = "uid://b8cmm5d5rblk2"
const ICON_LINK_ON: String = "uid://d0g35wgxg8nw0"
const ICON_LINK_OFF: String = "uid://b8mnnprmi58s7"
const ICON_SPEED: String = "uid://baq21vg514u8g"
const ICON_SPEED_RESET: String = "uid://nw3kmh6k8ub2"
const ICON_ALIGN_LEFT: String = "uid://cs5gw1ggpwy1y"
const ICON_ALIGN_RIGHT: String = "uid://cc1kk6brs435o"
const ICON_ALIGN_TOP: String = "uid://dta1i7dgsv5c5"
const ICON_ALIGN_BOTTOM: String = "uid://ctj8bypf2vto7"
const ICON_ALIGN_CENTER: String = "uid://bmmoevoo8eyxv"
const ICON_ALIGN_FILL: String = "uid://ct08ewt2hqgxj"
const ICON_FILE_VIDEO: String = "uid://bbbs474i3jn8p"
const ICON_MODULE_MANAGER: String = "uid://dv8hc4nyek87r"
const ICON_COMMAND_PROMPT: String = "uid://c01qwrnswdp6m"
const ICON_BUG: String = "uid://dbii66td26llk"

const SHADER_IMAGE_TO_YUV: String = "uid://bs1u3w6ry2hoa"
const SHADER_YUV420P: String = "res://shaders/yuv420p_standard.glsl"
const SHADER_YUV420P_FULL: String = "res://shaders/yuv420p_full.glsl"

const THUMB_DEFAULT_AUDIO: String = "uid://cs5gcg8kix42x"
const THUMB_DEFAULT_VIDEO: String = "uid://dpg11eiuwgv38"
const THUMB_DEFAULT_TEXT: String = "uid://nkyfxrdl2o8"

const BUTTON_CLIP: String = "uid://cvdbyqqvy1rl1"
const BUTTON_MARKER: String = "uid://dvp6a4xgk5pa8"

const STYLE_BOX_CLIP_IMAGE_NORMAL: String = "uid://dlxa6tecfxvwa"
const STYLE_BOX_CLIP_IMAGE_FOCUS: String = "uid://bwnfn42mtulgg"
const STYLE_BOX_CLIP_AUDIO_NORMAL: String = "uid://b4hr3qnksucav"
const STYLE_BOX_CLIP_AUDIO_FOCUS: String = "uid://dxu1itu4lip5q"
const STYLE_BOX_CLIP_VIDEO_NORMAL: String = "uid://dvjs7m2ktd528"
const STYLE_BOX_CLIP_VIDEO_FOCUS: String = "uid://wied1chri6pt"
const STYLE_BOX_CLIP_COLOR_NORMAL: String = "uid://df0jxk11tracv"
const STYLE_BOX_CLIP_COLOR_FOCUS: String = "uid://cwxo126dikkbh"
const STYLE_BOX_CLIP_TEXT_NORMAL: String = "uid://c8iincian78e3"
const STYLE_BOX_CLIP_TEXT_FOCUS: String = "uid://vtif6uw34cqe"
const STYLE_BOX_CLIP_PCK_NORMAL: String = "uid://d4imyv73ke52c"
const STYLE_BOX_CLIP_PCK_FOCUS: String = "uid://cbbl73i1eow1v"
const STYLE_BOX_CLIP_PREVIEW: String = "uid://dx2v44643hfvy"

const STYLE_LINE_TRACK: String = "uid://ccq8hdcqq8xrc"

const THEME_DEFAULT: String = "uid://715mkakin2bb"

const FONT_ROBOTO_MEDIUM: String = "uid://bnubhr3uus8gt"
const FONT_ROBOTO_REGULAR: String = "uid://dq00mn4msotdf"

const EFFECT_TEXT: String = "uid://bl6l8k0pk0bew"

const EFFECT_VISUAL_TRANSFORM: String = "uid://4mtlh3uaahui"

const EFFECT_AUDIO_VOLUME: String = "uid://dxp7sisypvq8b"

const COLOR_GOZEN_ACCENT: Color = Color(0.65, 0.1, 0.95, 0.4)
