name: Setup Linux Deps
description: Installs build dependencies
runs:
  using: composite
  steps:
    - name: Install dependencies
      shell: bash
      run: |
        sudo add-apt-repository -y ppa:git-core/ppa
        sudo apt-get update
        sudo apt-get install -y git yasm nasm python3 python3-pip scons gcc diffutils make \
        cmake autoconf automake libtool ninja-build pkg-config \
        binutils-aarch64-linux-gnu gcc-aarch64-linux-gnu \
        libnuma-dev fuse libfuse2 desktop-file-utils patchelf rpm
