name: Setup Godot
description: Downloads and configures Godot
inputs:
  godot-version:
    required: true
    description: e.g. 4.6-stable
  os:
    required: true
    default: linux

runs:
  using: composite
  steps:
    - name: Install Godot (Linux)
      if: inputs.os == 'linux'
      shell: bash
      env:
        GODOT_VERSION: ${{ inputs.godot-version }}
      run: |
        TEMPLATE_VERSION="${GODOT_VERSION/-/.}"

        echo "Setting up Godot $GODOT_VERSION..."
        mkdir -p ~/.local/bin

        echo "Downloading Godot Editor..."
        wget -q -O godot_linux.zip "https://github.com/godotengine/godot-builds/releases/download/${GODOT_VERSION}/Godot_v${GODOT_VERSION}_linux.x86_64.zip"
        unzip -o godot_linux.zip
        mv Godot_v${GODOT_VERSION}_linux.x86_64 ~/.local/bin/godot
        chmod +x ~/.local/bin/godot
        rm godot_linux.zip

        TEMPLATES_PATH=~/.local/share/godot/export_templates/${TEMPLATE_VERSION}

        echo "Downloading Export Templates..."
        wget -q -O godot_templates.tpz "https://github.com/godotengine/godot-builds/releases/download/${GODOT_VERSION}/Godot_v${GODOT_VERSION}_export_templates.tpz"

        mkdir -p "$TEMPLATES_PATH"
        unzip -q -o godot_templates.tpz -d /tmp/godot_templates
        mv /tmp/godot_templates/templates/* "$TEMPLATES_PATH"/
        rm -rf /tmp/godot_templates godot_templates.tpz

    - name: Add Godot to PATH (Linux)
      if: inputs.os == 'linux'
      shell: bash
      run: echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: Install Godot (Windows)
      if: inputs.os == 'windows'
      shell: bash
      env:
        GODOT_VERSION: ${{ inputs.godot-version }}
      run: |
        TEMPLATE_VERSION="${GODOT_VERSION/-/.}"
        INSTALL_DIR="C:/Program Files/Godot"
        mkdir -p "$INSTALL_DIR"

        # Editor
        echo "Downloading Godot Editor (Windows)..."
        curl -L -o godot_win.zip "https://github.com/godotengine/godot-builds/releases/download/${GODOT_VERSION}/Godot_v${GODOT_VERSION}_win64.exe.zip"
        unzip -q -o godot_win.zip
        mv Godot_v${GODOT_VERSION}_win64.exe "$INSTALL_DIR/godot.exe"
        rm godot_win.zip

        # Templates
        APPDATA_PATH=$(cygpath "$APPDATA")/Godot/export_templates/${TEMPLATE_VERSION}
        echo "Downloading Templates (Windows)..."
        curl -L -o templates.tpz "https://github.com/godotengine/godot-builds/releases/download/${GODOT_VERSION}/Godot_v${GODOT_VERSION}_export_templates.tpz"
        mkdir -p "$APPDATA_PATH"
        unzip -q -o templates.tpz -d temp_templates
        mv temp_templates/templates/* "$APPDATA_PATH"/
        rm -rf temp_templates templates.tpz

    - name: Add Godot to PATH (Windows)
      if: inputs.os == 'windows'
      shell: bash
      run: echo "C:/Program Files/Godot" >> $GITHUB_PATH
