import os
import build_ffmpeg


env = SConscript('../godot_cpp/SConstruct')
env.Append(CPPPATH=['src/'])
env.Append(LIBS=['avcodec', 'avformat', 'avfilter', 'avdevice', 'avutil', 'swscale', 'swresample'])

num_jobs = ARGUMENTS.get('jobs', 4)
platform = ARGUMENTS.get('platform', 'Linux')
use_mingw = ARGUMENTS.get('use_mingw', 'no')

if platform == 'windows':
    # Adding libraries for building
    build_ffmpeg(num_jobs)
    env.Append(CPPPATH=['ffmpeg_bin/include'])
    env.Append(LIBPATH=['ffmpeg_bin/bin'])
    if use_mingw == 'no': # Mingw is used for compiling on Linux for Windows
        env.Append(LINKFLAGS=['avcodec.lib', 'avformat.lib', 'avfilter.lib', 'avdevice.lib', 'avutil.lib', 'swscale.lib', 'swresample.lib'])

sharedlib = env.SharedLibrary('../bin/libgozen{}{}'.format(env['suffix'], env['SHLIBSUFFIX']), source=Glob('src/*.cpp'))
Default(sharedlib)
