name: Setup FFmpeg
description: Downloads and installs pre-compiled FFmpeg libraries from the latest CI run
inputs:
  os:
    required: true
    description: linux or windows
  arch:
    required: false
    default: x86_64
  token:
    required: true
    description: GITHUB_TOKEN is required to query workflow runs

runs:
  using: composite
  steps:
    - name: Get latest Run ID for "Compile FFmpeg"
      id: get-run-id
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.token }}
      run: |
        WORKFLOW_NAME="Compile FFmpeg"
        
        # Fetch the latest successful run ID.
        LATEST_RUN_ID=$(gh run list --workflow "$WORKFLOW_NAME" --status success --json databaseId --jq '.[0].databaseId')

        if [ -z "$LATEST_RUN_ID" ]; then
          echo "::error::Could not find a successful run for workflow '$WORKFLOW_NAME'."
          exit 1
        fi

        echo "Found Run ID: $LATEST_RUN_ID"
        echo "run_id=$LATEST_RUN_ID" >> $GITHUB_OUTPUT

    - name: Download FFmpeg Artifact
      uses: actions/download-artifact@v4
      with:
        name: ffmpeg_${{ inputs.os }}_${{ inputs.arch }}
        github-token: ${{ inputs.token }}
        run-id: ${{ steps.get-run-id.outputs.run_id }}
        path: ./core/ffmpeg/bin_${{ inputs.os }}

    - name: Copy libs (Linux)
      if: inputs.os == 'linux'
      working-directory: ./core
      shell: bash
      run: |
        echo "Copying FFmpeg libraries for Linux..."
        python3 -c "import sys; sys.path.append('.'); import build_ffmpeg; build_ffmpeg.copy_lib_files_linux('${{ inputs.arch }}')"

    - name: Install Python 3.11 on Windows
      if: inputs.os == 'windows'
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Copy libs (Windows)
      if: inputs.os == 'windows'
      working-directory: ./core
      shell: pwsh
      run: |
        Write-Host "Copying FFmpeg libraries for Windows..."
        python -c "import sys; sys.path.append('.'); import build_ffmpeg; build_ffmpeg.copy_lib_files_windows_ci('${{ inputs.arch }}')"
