on: [push, pull_request]

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Setup Python
        uses: actions/setup-python@v5
      - name: Setup SCons
        run: pip install scons
      - name: Setup Yasm
        run: sudo apt install -y yasm
      - name: Build FFmpeg
        run: pushd ./src/bin/gde_ffmpeg/ && sh ./build-ffmpeg.sh && popd
      - name: Build GDExtension
        run: pushd ./src/bin/gde_ffmpeg/ && scons target=template_release platform=linux use_ci=yes && popd
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ffmpeg-linux
          path: "**/libgozen*"
