name: Build RPM Package
on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string

env:
  GODOT_VERSION: 4.4.1
  EXPORT_FOLDER: libs/bin/linux_x86_64
  APP_NAME: gozen
  RPM_BUILD_DIR: ${{ github.workspace }}/rpmbuild

run-name: 'RPM version: ${{ inputs.version }} by @${{ github.actor }}'
jobs:
  build-rpm:
    name: Build RPM Package
    permissions:
      actions: read
      contents: read
    runs-on: ubuntu-22.04
    container:
      image: fedora:latest
    steps:
      - name: Install dependencies
        run: dnf install -y rpm-build git tar gzip desktop-file-utils gpg

      - name: Checkout submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Download Linux Artifact
        uses: actions/download-artifact@v4
        with:
          name: GoZen_Linux_x86_64_${{ inputs.version }}
          path: ${{ env.EXPORT_FOLDER }}

      - name: Parse version
        id: version
        run: |
          FULL_VERSION=${{ inputs.version }}
          VERSION_CLEAN=$(echo "$FULL_VERSION" | sed -E 's/^v//; s/-.*//')
          RELEASE_CLEAN=$(echo "$FULL_VERSION" | grep -oP '(?<=-).*' || echo "1")

          echo "version=$VERSION_CLEAN" >> $GITHUB_OUTPUT
          echo "release=$RELEASE_CLEAN" >> $GITHUB_OUTPUT

      - name: Prepare RPM structure
        run: |
          mkdir -p ${{ env.RPM_BUILD_DIR }}/{BUILD,RPMS,SOURCES,SPECS,SRPMS}
          mkdir -p ${{ env.RPM_BUILD_DIR }}/SOURCES/${{ env.APP_NAME }}-${{ steps.version.outputs.version }}

          cp -r ${{ env.EXPORT_FOLDER }}/* ${{ env.RPM_BUILD_DIR }}/SOURCES/${{ env.APP_NAME }}-${{ steps.version.outputs.version }}
          chmod +x ${{ env.RPM_BUILD_DIR }}/SOURCES/${{ env.APP_NAME }}-${{ steps.version.outputs.version }}/GoZen.x86_64

          sed -i 's|^Exec=.*|Exec=/opt/GoZen.x86_64|' gozen.desktop
          cp gozen.desktop ${{ env.RPM_BUILD_DIR }}/SOURCES/${{ env.APP_NAME }}-${{ steps.version.outputs.version }}/
          cp assets/gozen_icon.png ${{ env.RPM_BUILD_DIR }}/SOURCES/${{ env.APP_NAME }}-${{ steps.version.outputs.version }}/

          tar -czf ${{ env.RPM_BUILD_DIR }}/SOURCES/${{ env.APP_NAME }}-${{ steps.version.outputs.version }}.tar.gz -C ${{ env.RPM_BUILD_DIR }}/SOURCES ${{ env.APP_NAME }}-${{ steps.version.outputs.version }}


      - name: Create RPM spec file
        run: |
          cat <<EOF > ${{ env.RPM_BUILD_DIR }}/SPECS/${{ env.APP_NAME }}.spec
          %global debug_package %%{nil}
          Name:           ${{ env.APP_NAME }}
          Version:        ${{ steps.version.outputs.version }}
          Release:        0.${{ steps.version.outputs.release }}%{?dist}
          Summary:        GoZen video editor
          License:        GPLv3
          Source0:        %{name}-%{version}.tar.gz
          BuildArch:      x86_64

          %description
          GoZen is a lightweight and modern video editor written in Godot.

          %prep
          %setup -q

          %install
          mkdir -p %{buildroot}/opt/${{ env.APP_NAME }}
          cp -a * %{buildroot}/opt/${{ env.APP_NAME }}

          mkdir -p %{buildroot}/usr/share/applications
          cp gozen.desktop %{buildroot}/usr/share/applications/

          mkdir -p %{buildroot}/usr/share/icons/hicolor/128x128/apps
          cp gozen_icon.png %{buildroot}/usr/share/icons/hicolor/128x128/apps/${{ env.APP_NAME }}.png

          %files
          /opt/${{ env.APP_NAME }}
          /usr/share/applications/gozen.desktop
          /usr/share/icons/hicolor/128x128/apps/${{ env.APP_NAME }}.png

          %changelog
          * $(date +"%a %b %d %Y") Voylin <voylinslife@gmail.com> - ${{ inputs.version }}-1
          - Initial RPM build
          EOF

      - name: Build RPM
        run: rpmbuild --define "_topdir ${{ env.RPM_BUILD_DIR }}" -ba ${{ env.RPM_BUILD_DIR }}/SPECS/${{ env.APP_NAME }}.spec

      - name: Fix RPM path
        run: |
          mkdir -p /__w/gozen/gozen/rpm
          cp ${{ env.RPM_BUILD_DIR }}/RPMS/x86_64/* /__w/gozen/gozen/rpm/

      - name: Upload RPM
        uses: actions/upload-artifact@v4
        with:
          name: GoZen_Linux_RPM_${{ inputs.version }}
          path: rpm
          if-no-files-found: error

